### ISSUE TITLE
Able to create an account with an extra long name that breaks the UI

### ISSUE THREAD

**Issue by twjsanderson** [intrvertmichael/twttr#1]
**When registering a new account I can create an extra long name with no restrictions for length. This breaks the UI and overflows onto the posts section. It is replicated when I create posts of my own, spilling into the white space of the screen.

Tested on Chrome, Ubuntu, Desktop and Mobile (425 x 367)**

![twitterlongname](https://user-images.githubusercontent.com/43800258/98874095-8eae5600-2447-11eb-92ae-838b1d78d947.png)

![newentrylong](https://user-images.githubusercontent.com/43800258/98874105-953ccd80-2447-11eb-916b-075984ab8b3b.png)

**Comment by intrvertmichael** [comment]
Hey @twjsanderson thanks for the feedback.
This issue should now be fixed. Max length is now 20 characters.
